export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="font-[var(--font-heading)] text-3xl font-bold mb-8 text-gold">About Asterpredict</h1>

      <div className="space-y-8 text-muted leading-relaxed">
        <section>
          <h2 className="font-[var(--font-heading)] text-xl font-bold text-foreground mb-3">What is Asterpredict?</h2>
          <p>
            Asterpredict is an AI-powered market prediction platform focused on the{" "}
            <a href="https://www.asterdex.com/en" target="_blank" rel="noopener noreferrer" className="text-accent hover:underline">
              Aster DEX
            </a>{" "}
            ecosystem and the broader DeFi perpetuals market. Our AI assistant, Kage,
            analyzes on-chain data, market sentiment, and price action to deliver
            directional predictions and insights.
          </p>
        </section>

        <section>
          <h2 className="font-[var(--font-heading)] text-xl font-bold text-foreground mb-3">How It Works</h2>
          <ol className="list-decimal pl-5 space-y-2">
            <li>We fetch real-time market data from public APIs (price, volume, trends)</li>
            <li>This data is fed into an advanced reasoning AI model for multi-step analysis</li>
            <li>The model applies multi-step analysis considering price action, volume, sentiment, and macro factors</li>
            <li>Predictions are delivered with a directional call (bullish/bearish/neutral), confidence score, and transparent reasoning</li>
          </ol>
        </section>

        <section>
          <h2 className="font-[var(--font-heading)] text-xl font-bold text-foreground mb-3">About Aster DEX</h2>
          <p>
            Aster is a privacy-focused decentralized exchange offering perpetual markets on
            crypto, stocks, and commodities. Built on its own Layer 1 chain with 100K+ TPS,
            Aster features hidden orders, up to 1001x leverage, and multi-chain access
            across BNB Chain, Ethereum, Solana, and Arbitrum. Backed by YZi Labs (formerly
            Binance Labs).
          </p>
        </section>

        <section className="ink-card rounded-xl p-6">
          <h2 className="font-[var(--font-heading)] text-xl font-bold text-accent-red mb-3">⚠️ Disclaimer</h2>
          <div className="space-y-3 text-sm">
            <p>
              <strong className="text-foreground">This is NOT financial advice.</strong>{" "}
              Asterpredict AI predictions are generated by artificial intelligence and are
              for informational and entertainment purposes only.
            </p>
            <p>
              AI models can and do make mistakes. Past predictions do not guarantee future
              accuracy. Cryptocurrency markets are highly volatile and you can lose your
              entire investment.
            </p>
            <p>
              <strong className="text-foreground">Always do your own research (DYOR).</strong>{" "}
              Never invest more than you can afford to lose.
            </p>
            <p>
              Asterpredict is an independent community project and is not officially
              affiliated with, endorsed by, or sponsored by Aster DEX or its parent entities.
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-[var(--font-heading)] text-xl font-bold text-foreground mb-3">Technology</h2>
          <ul className="space-y-1 text-sm">
            <li>• <strong>AI Model:</strong> Advanced Reasoning LLM</li>
            <li>• <strong>Market Data:</strong> CoinGecko API</li>
            <li>• <strong>Frontend:</strong> Next.js + Tailwind CSS</li>
            <li>• <strong>Design:</strong> Ink Wash Game Aesthetic</li>
          </ul>
        </section>

        <section>
          <h2 className="font-[var(--font-heading)] text-xl font-bold text-foreground mb-3">Contact</h2>
          <p>
            Follow us on{" "}
            <a href="https://x.com/Asterpredict" target="_blank" rel="noopener noreferrer" className="text-accent hover:underline">
              Twitter/X @Asterpredict
            </a>{" "}
            for daily predictions and market insights.
          </p>
        </section>
      </div>
    </div>
  );
}
